update

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -58,18 +58,18 @@ jobs:
           fi
           echo "SSH setup completed successfully"
 
-      - name: Debug SSH key setup
-        run: |
-          echo "Debugging SSH key setup"
-          ssh-add -l || echo "SSH key not found"
-          echo "Known hosts:"
-          cat ~/.ssh/known_hosts || echo "No known hosts found"
-          echo "SSH agent status:"
-          ps aux | grep ssh-agent || echo "SSH agent not running"
-          exit 1  # Force exit to see the debug output
+      # Commenting out Debug SSH key setup
+      #      - name: Debug SSH key setup
+      #        run: |
+      #          echo "Debugging SSH key setup"
+      #          ssh-add -l || echo "SSH key not found"
+      #          echo "Known hosts:"
+      #          cat ~/.ssh/known_hosts || echo "No known hosts found"
+      #          echo "SSH agent status:"
+      #          ps aux | grep ssh-agent || echo "SSH agent not running"
+      #          exit 1  # Force exit to see the debug output
 
       - name: Deploy to EC2
-        if: always() # This will run even if the previous step fails
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.EC2_HOST }}
